#┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#┃  JPCraftLobby                        ┃
#┃              by nennneko5787         ┃
#┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# コンフィグのバージョンです、"絶対に"変更しないでください！
version: 0.2-ALPHA

#┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#┃             システム設定              ┃
#┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

system:
  # プラグインの優先度。
  # LOWEST で他のプラグインの判断が優先され、 HIGHEST でこのプラグインが最も優先されるようになります。
  # 利用可能な値: LOWEST, LOW, NORMAL, HIGH, HIGHEST
  priority: HIGH


#┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#┃             チャット設定              ┃
#┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# 連投防止
anti-spam:
  # チャットカウンタのリセットまでの秒数。
  counter-reset: 10
  # counter-reset秒の間何回までチャットができるか。
  chat-count: 6
  # counter-reset秒の間にchat-count回以上チャットを送信しようとした時の通知設定
  notifications:
    # 連投した場合に警告を送信するかどうか。
    enable: true
    # 連投した場合の警告メッセージ。
    # 色を付けるには、§や&ではなく、MiniMessageの記法を使用してください。
    # MiniMessage viewer: https://webui.advntr.dev/
    # 以下の変数が利用可能です。
    # {{counter-reset}} -> config.yml anti-spam.counter-reset
    # {{chat-count}} -> config.yml anti-spam.chat-count
    message: "[JPCraftLobby] &c連投し過ぎです。{{counter-reset}}秒に{{chat-count}}回までチャットを送信できます。"

# NGワードをマスク
# 完全にブロックしたい場合は、ngword-blockを使うことをおすすめします。
ngword-mask:
  # NGワード(マスク)。ここに追加したワードは後述するmaskでマスクされます。
  # 正規表現が利用可能です。
  words:
    - ちん(ぽ|こ|ちん)

  # NGワードをマスクするために使う文字。
  # 必ずしも1文字でなければならないわけではありません。
  mask: "*"

  # NGワードの通知設定
  notifications:
    # NGワードがあった場合に警告を送信するかどうか。
    enable: true
    # NGワードがあった場合の警告メッセージ。
    # 該当ワードをメッセージ内に書くには、{{word}}をメッセージに含めてください。
    message: "[JPCraftLobby] &cメッセージは送信されましたが、メッセージに禁止ワードが含まれています。 該当ワード: {{word}}"

# NGワードをブロック
ngword-block:
  # NGワード(ブロック)。ここに追加したワードを送信しようとすると、ブロックされます。
  # 正規表現が利用可能です。
  words:
    - 障(害|碍|がい)者
    - (死|氏|し)ね
    - (基地|キチ|きち)(外|ガイ|がい)

  # NGワードの通知設定
  notifications:
    # NGワードがあった場合に警告を送信するかどうか。
    enable: true
    # NGワードがあった場合の警告メッセージ。
    # 該当ワードをメッセージ内に書くには、{{word}}をメッセージに含めてください。
    message: "[JPCraftLobby] &cあなたは禁止ワードを送信したため、メッセージの送信をブロックしました。 該当ワード: {{word}}"

# プレイヤーミュート設定
mutes:
  # ミュートされているユーザーがチャットを送信しようとしたときに表示されるメッセージ。
  message: "[JPCraftLobby] &cあなたはミュートされています！"
