name: Maven Clean Install

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jpcraftlobby-v0.2-ALPHA
        path: /target/jpcraftlobby-v0.2-ALPHA.jar  # 成果物のパスを指定します
